
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://52.221.242.52:3306/audici_oauth?createDatabaseIfNotExist=true
    username: buddhika
    password: some_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  application:
    name: Audici-Oauth-Service

