spring:
  datasource:
    url: jdbc:mysql://52.221.242.52:3306/audici_oauth?createDatabaseIfNotExist=true
    username: buddhika
    password: some_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

  application:
    name: Audici-UserManagement-Service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
security:
  oauth2:
    resource:
      token-info-uri: http://3.1.218.83:8080/oauth/check_token
    client:
      client-id: audici_client
      client-secret: test
server:
  port: 8081
storage:
  location: ./uploads
